packages:
  - 'packages/lint/*'

overrides:
  'typescript': '^5.9.2'
  eslint: '^9.32.0'
  lerna: ^8.2.3
  stylelint: ^16.23.0

catalogs:
  prod:
    vue-eslint-parser: ^10.2.0
    '@stylistic/eslint-plugin': ^5.2.2
    eslint-import-resolver-typescript: ^4.4.4
    eslint-plugin-import: ^2.32.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-vue: ^10.4.0
    globals: ^16.3.0
    typescript-eslint: ^8.39.0
    '@eslint/config-helpers': ^0.3.1

  peer:
    eslint: ^9.32.0
    stylelint: ^16.23.0
  
  dev:
    typescript: ^5.9.2
    vitest: ^3.2.4
    tsdown: ^0.14.0
    ts-node: ^10.9.2
    lerna: ^8.2.3
    cross-env: ^10.0.0
    '@types/eslint-plugin-jsx-a11y': ^6.10.0
    '@types/node': ^24.2.0